### ISSUE TITLE
ImportError: libopenblas.so.0 // Refusing websocket connection

### ISSUE THREAD

**Issue by bs7** [bokeh/bokeh-demos#19] opened 2016-01-22 11:47 UTC
<b>Error 1</b>
conda create -n Name --file conda-requirements.txt
source activate Name
./bokeh.sh
==> ImportError: libopenblas.so.0

My solution: conda update numpy

<b>Error 2</b>
Starting development server at http://127.0.0.1:8001/
==> ERROR:bokeh.server.views.ws:Refusing websocket connection...

My solution: --allow-websocket-origin=127.0.0.1:8001

<b>Question</b>
I started bokeh server in debug modus and looked what happens to the number of clients. Everytime I choose an Employee the number of clients increases 1, 2, ... 6 ..., after sometime some websocket connections are closed and the number of clients reduces. Is there a way to control this?

**Comment by birdsarah** [comment] 2016-01-23 01:03
Not sure what's going on with the two errors, maybe you could share more about your setup?

> Everytime I choose an Employee the number of clients increases 1, 2, ... 6 ..., after sometime some websocket connections are closed and the number of clients reduces. Is there a way to control this?
Yes, this is a mistake on my part (didn't call session.close() after pull_session) - I'm working on an update to this app at the moment which will hopefully be simpler and cleaner and will scale better.

Should be done by Monday.

**Comment by birdsarah** [comment] 2016-01-23 03:08
It's worth saying that half of the client connections are inappropriate, half, I believe aren't. When you clieck on a new Employee on the left it's simulating a user logging in in another browser. I didn't implement a full login as it would make it somewhat of a pain to explore the app. But that's the idea. I think I'm just going to implement the login in this next round of development to make it clear.

**Comment by birdsarah** [comment] 2016-01-24 00:13
@bs7 I have observed the libblas problem and am working on a fix.

I can't reproduce the `Refusing websocket connection...` error - can you give more information.

**Comment by birdsarah** [comment] 2016-01-24 00:31
Fix pushed for libblas problem: https://github.com/bokeh/bokeh-demos/pull/20
(the answer was to use an environment.yml and not a conda-requirements file - environment.yml is much nicer to read too)

**Comment by birdsarah** [comment] 2016-01-24 00:31
I'm going to close this, feel free to open a new issue about the websocket issue if it persists.

**Closed by birdsarah** 2016-01-24 00:31 UTC
